name: connecttoec2

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "siddhu" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-109-32-37.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      # Test SSH connection
      - name: Test SSH
        run: |
          ssh -i ~/.ssh/id_rsa traiflix@ec2-3-109-32-37.ap-south-1.compute.amazonaws.com "echo ✅ Connected to EC2"
