name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "siddhu" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $ec2-3-109-32-37.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      # 3️⃣ Test SSH connection
      - name: Test SSH
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$ec2-3-109-32-37.ap-south-1.compute.amazonaws.com "echo ✅ Connected to EC2"

      # 4️⃣ Deploy the repo
      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$ec2-3-109-32-37.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~/myproject || https://github.com/srinivasarao3234/smartail-assignment.git ~/myproject
            cd ~/myproject
            git reset --hard
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
